---
- hosts: all
  connection: local

  vars:
    - is_macos: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_os_family == 'Ubuntu'

  tasks:
    # Essentials
    - include: tasks/homebrew.yml
