---
- hosts: all
  connection: local

  vars:
    - is_macos: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'

  tasks:
    # essentials
    - include: tasks/homebrew.yml

    # editors, IDEs, terminals, etc.
    - include: tasks/vim.yml

    # languages
    - include: tasks/ruby.yml
