---
- hosts: all
  connection: local

  vars:
    - is_macos: ansible_os_family == 'Darwin'
    - is_ubuntu: ansible_distribution == 'Ubuntu'

  tasks:
    # essentials
    - include: tasks/homebrew.yml
    - include: tasks/apt.yml
    - include: tasks/core.yml
    - include: tasks/dotfiles.yml

    # editors, IDEs, terminals, etc.
    - include: tasks/vim.yml
    - include: tasks/tmux.yml
    - include: tasks/vscode.yml

    # databases
    # TODO: Fix for Ubuntu
    #    - include: tasks/mysql.yml

    # languages
    - include: tasks/ruby.yml

    # tools
    #    - include: tasks/yarn.yml
    
    # chat
    - include: tasks/slack.yml

    # media
    - include: tasks/spotify.yml
