---
- name: Update Homebrew
  homebrew: update_homebrew=yes
  when: is_macos
- name: Add Homebrew taps
  homebrew_tap: tap={{ item }}
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
  when: is_macos
