---
- name: Add Spotify apt keys
  apt_key: keyserver=keyserver.ubuntu.com id=D2C19886
  when: is_ubuntu
- name: Add Spotify repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'
  when: is_ubuntu
- name: Install Spotify
  package: name=spotify-client
  when: is_ubuntu

